name: Build image and push to GHCR

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 4 * * 6' 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: github-runner

jobs:

  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
    - id: string
      uses: ASzc/change-string-case-action@v5
      with:
          string: ${{ github.repository_owner }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/${{ env.IMAGE_NAME }}:latest
    - name: Delete old images
      uses: snok/container-retention-policy@v2
      with:
          image-names: ${{ env.IMAGE_NAME }}
          keep-at-least: 3
          cut-off: one hour ago UTC
          timestamp-to-use: updated_at
          account-type: personal
          skip-tags: latest
          token: ${{ secrets.GH_TOKEN }}
